from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_RIGHT, TA_JUSTIFY
from datetime import datetime
import matplotlib.pyplot as plt
import os


# ---------------------------------------------------------
# Footer with page numbers
# ---------------------------------------------------------

def add_page_number(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    footer = "AI Product Feedback Analyzer • Confidential"

    canvas.drawString(
        doc.leftMargin,
        0.5 * inch,
        footer
    )

    page = f"Page {doc.page}"

    canvas.drawRightString(
        doc.pagesize[0] - doc.rightMargin,
        0.5 * inch,
        page
    )

    canvas.restoreState()


# ---------------------------------------------------------
# PDF
# ---------------------------------------------------------

def create_pdf(results, filename="Executive_Report.pdf"):

    doc = SimpleDocTemplate(
        filename,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=50
    )

    styles = getSampleStyleSheet()

    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.fontSize = 22
    title_style.leading = 26

    heading = styles["Heading1"]
    heading.textColor = colors.HexColor("#005A9C")
    heading.spaceBefore = 8
    heading.spaceAfter = 4

    body = styles["BodyText"]

    body.alignment = TA_JUSTIFY
    body.leading = 14
    body.spaceAfter = 4

    elements = []

    # =====================================================
    # Header with Logo
    # =====================================================

    logo_path = "assets/logo.png"

    if os.path.exists(logo_path):
        logo = Image(
            logo_path,
            width=1.8 * inch,
            height=0.45 * inch
        )
    else:
        logo = Spacer(1.8 * inch, 0.45 * inch)

    title = Paragraph(
        "<b>Product Feedback Report</b>",
        title_style
    )

    header = Table(
        [[title, logo]],
        colWidths=[5.2 * inch, 1.3 * inch]
    )

    header.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("RIGHTPADDING", (1,0), (1,0), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))

    elements.append(header)
    elements.append(Spacer(1, 12))

    elements.append(
        Paragraph(
            f"""
            <b>Generated:</b> {datetime.now().strftime('%B %d, %Y %I:%M %p')}<br/>
            <b>Prepared For:</b> Watts Water Technologies<br/>
            <b>Generated By:</b> AI Product Feedback Analyzer
            """,
            body
        )
    )

    elements.append(Spacer(1, 20))
    # =====================================================
    # Dashboard Metrics
    # =====================================================

    priorities = results["priorities"]["priorities"]

    high = sum(
        p["priority"].lower() == "high"
        for p in priorities
    )

    medium = sum(
        p["priority"].lower() == "medium"
        for p in priorities
    )

    low = sum(
        p["priority"].lower() == "low"
        for p in priorities
    )

    categories = len(results["categories"]["categories"])

    elements.append(
        Paragraph(
            "Executive Dashboard Metrics",
            heading
        )
    )

    metric_table = Table([
        ["Metric", "Value"],
        ["Categories", categories],
        ["High Priority", high],
        ["Medium Priority", medium],
        ["Low Priority", low]
    ])

    metric_table.setStyle(TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#005A9C")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("GRID", (0,0), (-1,-1), .5, colors.grey),

        ("BACKGROUND", (0,1), (-1,-1), colors.whitesmoke),

        ("BOTTOMPADDING", (0,0), (-1,0), 8)

    ]))

    elements.append(metric_table)

    elements.append(Spacer(1, 10))

     # =====================================================
    # Executive Summary
    # =====================================================

    elements.append(
        Paragraph(
            "Executive Summary",
            heading
        )
    )

    summary = results["executive_summary"]

    # Remove markdown symbols if present
    summary = (
        summary.replace("#", "")
               .replace("**", "")
    )

    # Split into lines
    lines = summary.splitlines()

    section_titles = [
        "Overview:",
        "Key Findings:",
        "Recommended Roadmap:",
        "Business Impact:",
        "Recommendation:"
    ]

    for line in lines:

        line = line.strip()

        if not line:
            elements.append(Spacer(1, 4))
            continue

        # Blue section headings
        if line in section_titles:

            elements.append(
                Paragraph(
                    f"<font color='#005A9C'><b>{line}</b></font>",
                    styles["Heading2"]
                )
            )

            elements.append(Spacer(1, 2))

        # Bold Sprint labels
        elif line.startswith("Sprint 1:"):

            elements.append(
                Paragraph(
                    f"<b>Sprint 1:</b> {line.replace('Sprint 1:', '').strip()}",
                    body
                 
                )
            )

            elements.append(Spacer(1, 6))

        elif line.startswith("Sprint 2:"):

            elements.append(
                Paragraph(
                    f"<b>Sprint 2:</b> {line.replace('Sprint 2:', '').strip()}",
                    body
                )
            )

            elements.append(Spacer(1, 6))

        elif line.startswith("Sprint 3:"):

            elements.append(
                Paragraph(
                    f"<b>Sprint 3:</b> {line.replace('Sprint 3:', '').strip()}",
                    body
                )
            )

            elements.append(Spacer(1, 6))

        # Bullet points under Key Findings
        elif line.startswith("- ") or line.startswith("* "):

            bullet = line[2:].strip()

            elements.append(
                Paragraph(
                    f"&bull; {bullet}",
                    body
                )
            )

            elements.append(Spacer(1, 4))

        else:

            elements.append(
                Paragraph(
                    line,
                    body
                )
            )

            elements.append(Spacer(1, 10))
    # =====================================================
    # Priority Table
    # =====================================================

    elements.append(
        Paragraph(
            "Product Priorities",
            heading
        )
    )

    table_data = [["Issue", "Priority"]]

    for item in priorities:
        table_data.append([
            item["issue"],
            item["priority"]
        ])

    priority_table = Table(
        table_data,
        colWidths=[4.5 * inch, 1.5 * inch]
    )

    priority_table.setStyle(TableStyle([

        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#003B6F")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.white),

        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),

        ("GRID", (0,0), (-1,-1), .5, colors.grey),

        ("BACKGROUND", (0,1), (-1,-1), colors.beige),

        ("BOTTOMPADDING", (0,0), (-1,0), 8)

    ]))

    elements.append(priority_table)

    elements.append(Spacer(1, 10))

    # =====================================================
    # Roadmap
    # =====================================================

    elements.append(
        Paragraph(
            "Three Sprint Product Roadmap",
            heading
        )
    )

    for sprint in results["roadmap"]["roadmap"]:

        elements.append(
            Paragraph(
                f"<font color='#005A9C'><b>{sprint['sprint']}</b></font><br/>{sprint['goal']}",

                body
            )
        )

        elements.append(Spacer(1, 8))

    elements.append(Spacer(1, 20))

    # =====================================================
    # Charts
    # =====================================================

    categories_data = results["categories"]["categories"]

    labels = [c["category"] for c in categories_data]
    counts = [c["count"] for c in categories_data]

    plt.figure(figsize=(6,4))
    plt.bar(labels, counts, color="#005A9C")
    plt.title("Customer Feedback Categories")
    plt.ylabel("Feedback Count")
    plt.grid(axis="y", alpha=0.3)
    plt.xticks(rotation=20)
    plt.tight_layout()

    bar_file = "bar_chart.png"

    plt.savefig(bar_file)

    plt.close()

    elements.append(
        Paragraph(
            "Issue Frequency",
            heading
        )
    )

    bar = Image(
        bar_file,
        width=5.7 * inch,
        height=3.2 * inch
    )

    bar.hAlign = "CENTER"

    elements.append(bar)

    plt.figure(figsize=(5,5))
    plt.pie(
        counts,
        labels=labels,
        autopct="%1.0f%%"
    )
    plt.tight_layout()

    pie_file = "pie_chart.png"

    plt.savefig(pie_file)

    plt.close()

    elements.append(
        Paragraph(
            "Issue Distribution",
            heading
        )
    )

    pie = Image(
        pie_file,
        width=4.5*inch,
        height=4.5*inch
    )

    pie.hAlign = "CENTER"

    elements.append(pie)

    # =====================================================
    # Jira Stories
    # =====================================================
    elements.append(Spacer(1, 20))
    if "stories" in results:

        elements.append(
            Paragraph(
                "AI Generated Jira Stories",
                heading
            )
        )

        for story in results["stories"]["stories"]:

            elements.append(
                Paragraph(
                    f"<b>{story['id']}</b> — {story['title']}",
                    styles["Heading2"]
                )
            )

            elements.append(
                Paragraph(
                    f"<font color='#005A9C'><b>Priority:</b> {story['priority']}</font>",
                    body
                )
            )

            elements.append(
                Paragraph(
                    story["description"],
                    body
                )
            )

            elements.append(
                Paragraph(
                    "<b>Acceptance Criteria</b>",
                    body
                )
            )

            for item in story["acceptance"]:
                elements.append(
                    Paragraph(
                        f"• {item}",
                        body
                    )
                )

            elements.append(Spacer(1,15))

    # =====================================================
    # Build PDF
    # =====================================================

    doc.build(
        elements,
        onFirstPage=add_page_number,
        onLaterPages=add_page_number
    )
    if os.path.exists(bar_file):
        os.remove(bar_file)

    if os.path.exists(pie_file):
        os.remove(pie_file)

    return filename